---
title: "Exploratory Data Analysis"
author: "Trevor Barnes"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***Exploratory data analysis***, or ***EDA***, is a comparatively new area of statistics. Classical statistics focused almost exclusively on *inference*, a sometimes complex set of procedures for drawing conclusions about large populations based on small samples. With the ready availability of computing power and expressive data analysis software, exploratory data analysis has evolved well beyond its original scope. Key drivers of this discipline have been the rapid development of new technology, access to more and bigger data, and the greater use of quantitative analysis in a variety of disciplines.

___

## Elements of Structured Data

Data comes from many sources: sensor measurements, events, text, images, and videos. The *Internet of Things (IoT)* is spewing out streams of information. Much of this data is *unstructured*: images are a collection of pixels with each pixel containing RGB (red, green, blue) color information. Texts are sequences of words and nonword characters, often organized by sections, subsections, and so on. *Clickstreams* are sequences of actions by a user interacting with an app or web page. In fact, a major challenge of data science is to harness this torrent of raw data into actionable information. 

| Term | Definition|Synonym|
|-------|-------|------|
| **Continuous** | Data that can take on any value in an interval. | interval, float, numeric|
| **Discrete** | Data that can take only integer values, such as counts. | integer, count | 
| **Categorical** | Data that can take on only a specific set of values representing a set of possible categories. | enums, enumerated, factors, nominal, polychotomous|
| **Binary** | A special case of categorical data with just two categories of values (0/1, true/false). | dichotomous, logical, indicator, boolean |
| **Ordinal** | Categorical data that has an explicit ordering. | ordered factor |
Table: **Key Terms for Data Types**

There are two basic types of structured data: ***numeric*** and ***categorical***. *Numeric* data comes in two forms: ***continuous***, such as wind speed or time duration, and ***discrete***, such as the count of the occurrence of an event. *Categorical* data takes only a fixed set of values, such as a type of TV screen (plasma, LCD, LED, etc.) or a state name (Alabama, Alaska, etc.). ***Binary*** data is an important special case of *categorical* data that takes on only one of two values, such as 0/1, yes/no, or true/false. Another useful type of categorical data is ***ordinal*** data in which the categories are ordered; an example of this is a numerical rating (1, 2, 3, 4, or 5).

Knowing that data is categorical can act as a signal telling software how statistical procedures, such as producing a chart or fitting a model, should behave. In particular, ordinal data can be represented as an `ordered.factor` in R and Python, preserving a user-specified ordering in charts, tables, and models. This also allows us to optimize storage and indexing in a relational database or in Spark. The possible values a given categorical variable can take are enforced in the software (like an enum).

|Key Ideas|
|-----|
|Data is typically classified in software by type.|
|Data types include continuous, discrete, categorical (which includes binary), and ordinal.|
|Data typing in software acts as a signal to the software on how to process the data.|

___
## Rectangular Data

The typical frame of reference for an analysis in data science is a ***rectangular data*** object, like a spreadsheet or database table.

| Term | Definition | Synonym |
|-----|-----|-----|
